version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
  nginx:
    depends_on:
      - site
      - dashboard
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
      - ./conf:/etc/nginx/conf.d 
      - ./html:/tmp             
    ports:
      - "80:80"     
  api:
    build:
      dockerfile: Dockerfile
      context: './bolao-api'
    ports:
      - "8080:8080" 
    volumes:
      - /app/node_modules
      - ./bolao-api:/app
  site:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: './bolao'
    ports:
      - "3001:3001"  
    volumes:
      - /app/node_modules
      - ./bolao:/app
  dashboard:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: './Dashboard'
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./dashboard:/app
